version: '3.9'

services:
  notionintegration:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "3000:80"
    build:
      context: .
      dockerfile: NotionIntegration/Dockerfile