version: '3.9'

services:
  notionintegration:
    container_name: web
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "3000:80"
    build:
      context: .
      dockerfile: NotionIntegration/Dockerfile
    depends_on: [ mssql ]
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql
    hostname: mssql
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    ports:
      - "11433:1433"